import { db } from "../initiate-firebase.ts";

import { doc, setDoc, collection, getDocs, getDoc, addDoc } from "firebase/firestore"; 

export async function post(collectionName: string, id: string, data) {
    const docRef = doc(db, collectionName, id);
    return await setDoc(docRef, data, { merge: false })
}

// add document with autogenerated ID
export async function putDoc(collectionName: string, data) {
    const docRef = await addDoc(collection(db, collectionName), data).catch(console.error)
    return docRef    
}

export async function getAll(collectionName: string) {
    const querySnapshot = await getDocs(collection(db, collectionName))
    console.log(querySnapshot)
    querySnapshot.forEach((doc) => {
        console.log(doc.data())
    })
}

export async function doesBrokerExist(email: string) {
    const docRef = doc(db, "brokers", email)
    const document = await getDoc(docRef).catch(console.error)
    return document?.exists()? true: false
}
